CREATE TABLE IF NOT EXISTS transactions (
    id uuid PRIMARY KEY NOT NULL,
    description VARCHAR(255) NOT NULL,
    base_type VARCHAR(255) NOT NULL,
    amount FLOAT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);